version: "2"

services:
  fcrepo:
    image: oapass/fcrepo:4.7.5-3.1-SNAPSHOT@sha256:a10ed1961e8487f14ad29c3684c47f497cfd892f7364278013f094b4db6384a3
    container_name: fcrepo
    env_file: .env
    environment:
      - FCREPO_JMS_BASEURL=http://localhost:8080/fcrepo/rest
    ports:
      - "${FCREPO_PORT}:${FCREPO_PORT}"
      - "${FCREPO_JMS_PORT}:${FCREPO_JMS_PORT}"
      - "${FCREPO_STOMP_PORT}:${FCREPO_STOMP_PORT}"
      - "${FCREPO_DEBUG_PORT}:${FCREPO_DEBUG_PORT}"

  indexer:
    image: oapass/indexer:0.0.15-3.1-SNAPSHOT@sha256:17136594594a8816070cdb2068d3e24d3def389fa90b8729cd768124f3a9b8e9
    container_name: indexer
    env_file: .env
    links:
      - fcrepo:localhost
    volumes:
      - .docker/hosts:/etc/hosts:Z

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3@sha256:ccfad77c0731c010e6ff8c43b4ab50f5ce90c0fa4e65846530779c5c6707c20a
    container_name: elasticsearch
    env_file: .env
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - .docker/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:Z
    ports:
      - "${ES_PORT}:${ES_PORT}"

volumes:
  esdata:
    driver: local
